# Build stage
FROM node:18-alpine as BUILD_IMAGE
WORKDIR /app
COPY yarn.lock* .
RUN yarn --frozen-lockfile;
COPY . .
RUN yarn build

# Production Stage
FROM node:18-alpine as PROD_STAGE
WORKDIR /app
COPY --from=BUILD_IMAGE /app/package*.json ./
COPY --from=BUILD_IMAGE /app/.next ./.next
COPY --from=BUILD_IMAGE /app/public ./public
COPY --from=BUILD_IMAGE /app/node_modules ./node_modules
ENV NODE_ENV=production
EXPOSE 3000
CMD ["npm", "start"]
